### ISSUE TITLE
Can't run MeshTransformer.generate(return_codes = True)

### ISSUE THREAD

**Issue by fire** [lucidrains/meshgpt-pytorch#19]
MeshTransformer.generate(return_codes = True) fails for me. No need to rush for the weekend.

**Comment by lucidrains** [comment]
oh what kind of error do you see? i can put in one last fix before i head out with doggo

**Comment by lucidrains** [comment]
hmm, it runs for me

i'll address this Monday if you are hitting some edge case

**Comment by fire** [comment]
I captured some logs. 


```
██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3612/3612 [03:03<00:00, 19.66it/s]
Traceback (most recent call last):
  File "C:\Users\ernes\scoop\apps\python310\current\lib\site-packages\einops\einops.py", line 523, in reduce
    return _apply_recipe(
  File "C:\Users\ernes\scoop\apps\python310\current\lib\site-packages\einops\einops.py", line 234, in _apply_recipe
    init_shapes, axes_reordering, reduced_axes, added_axes, final_shapes, n_axes_w_added = _reconstruct_from_shape(
  File "C:\Users\ernes\scoop\apps\python310\current\lib\site-packages\einops\einops.py", line 187, in _reconstruct_from_shape_uncached
    raise EinopsError(f"Shape mismatch, can't divide axis of length {length} in chunks of {known_product}")
einops.EinopsError: Shape mismatch, can't divide axis of length 3611 in chunks of 3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\meshgpt-pytorch\inference.py", line 61, in <module>
    continuous_coors = transformer.autoencoder.decode_from_codes_to_faces(codes)
  File "<@beartype(meshgpt_pytorch.meshgpt_pytorch.MeshAutoencoder.decode_from_codes_to_faces) at 0x198ba48d1b0>", line 53, in decode_from_codes_to_faces
  File "C:\Users\ernes\scoop\apps\python310\current\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\meshgpt-pytorch\meshgpt_pytorch\meshgpt_pytorch.py", line 685, in decode_from_codes_to_faces
    face_mask = reduce(codes != self.pad_id, 'b (nf nv q) -> b nf', 'all', nv = 3, q = self.num_quantizers)
  File "C:\Users\ernes\scoop\apps\python310\current\lib\site-packages\einops\einops.py", line 533, in reduce
    raise EinopsError(message + "\n {}".format(e))
einops.EinopsError:  Error while processing all-reduction pattern "b (nf nv q) -> b nf".
 Input tensor shape: torch.Size([1, 3611]). Additional info: {'nv': 3, 'q': 1}.
 Shape mismatch, can't divide axis of length 3611 in chunks of 3
```

**Comment by lucidrains** [comment]
are you on the most recent version?

**Comment by fire** [comment]
I'm on a older version, there's another report the transformer broke, but take the weekend off, take care.

**Comment by fire** [comment]
I fixed it, the python pip needed a newer version of pooled attention

**Comment by lucidrains** [comment]
@fire oh nice, which package was it?

**Comment by fire** [comment]
One of your attention ones

**Comment by lucidrains** [comment]
@fire not very specific lol

**Comment by fire** [comment]
I’ll check when I’m at a computer

**Comment by lucidrains** [comment]
not a big deal, was just curious

glad it fixed itself!

**Comment by fire** [comment]
`'gateloop-transformer>=0.1.5',` was a few versions behind.

**Comment by lucidrains** [comment]
@fire ohh got it, that is actually not attention, but a new emerging technique (transformer is a misnomer)
